cornerstone/views/sermons.py
import logging

from flask import Blueprint, current_app, request

from cornerstone.db.models import Sermon
from cornerstone.sphinxapi import SphinxClient
from cornerstone.theming import render

log = logging.getLogger(__name__)
sermons = Blueprint('sermons', __name__)


class SermonsPage(object):
    title = 'Sermons'
    slug = 'sermons'


class SermonPage(object):
    title = 'Sermon'
    slug = 'sermon'


@sermons.route('/sermons', methods=['GET'])
def list():
    try:
        page_number = int(request.args.get('page', 1))
    except (ValueError, TypeError):
        page_number = 1
    query = None
    pagination = None
    if request.args.get('q', None):
        client = SphinxClient()
        client.SetServer(current_app.config.get('SPHINX_HOST', 'localhost'), current_app.config.get('SPHINX_PORT'))
        results = client.Query(request.args.get('q'))
        if results:
            query = Sermon.query.filter(Sermon.id.in_([m['id'] for m in results['matches']]))
        else:
            log.warning(client.GetLastError())
    else:
        query = Sermon.query
    if query:
        pagination = query.order_by(Sermon.date.desc()).paginate(page=page_number, per_page=10)
    page = SermonsPage()
    return render('sermons.html', pagination=pagination, page=page)


@sermons.route('/sermons/<id>', methods=['GET'])
def get(id):
    sermon = Sermon.get(id)
    page = SermonPage()
    return render('sermon.html', sermon=sermon, page=page)

cornerstone/templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <title>{% if page %}{{ page.title }} | {% endif %}{{config.get('CORNERSTONE_TITLE', 'CornerstoneCMS')}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      main {
        padding-top: 70px;
        padding-bottom: 15px;
      }
      .footer {
        background-color: #f5f5f5;
      }
      .footer > .container {
        padding-right: 15px;
        padding-left 15px;
      }
      .sweet-nectar {
        display: none;
      }
    </style>
  </head>
  <body class="d-flex flex-column h-100 {% if page %}{{page.slug}}{% endif %}">
    <header>
      <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="container">
          <a href="/" class="navbar-brand">
            {% if config.get('CORNERSTONE_LOGO') %}
            <img src="{{ config['CORNERSTONE_LOGO'] }}" width="30" height="30" class="d-inline-block align-top" alt="{{ config.get('CORNERSTONE_TITLE', 'CornerstoneCMS') }}">
            {% endif %}
            {{ config.get('CORNERSTONE_TITLE', 'CornerstoneCMS') }}
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
              {% for item in menu %}
              {% if item.has_children() %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="{{ item.slug }}-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ item.title }}</a>
                <div class="dropdown-menu" aria-labelledby="{{ item.slug }}-dropdown">
                  {% for child in item.children %}
                  <a class="dropdown-item {% if request.path == child.url %}active{% endif %}" href="{{ child.url }}">{{ child.title }}</a>
                  {% endfor %}
                </div>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link {% if request.path == item.url %}active{% endif %}" href="{{ item.url }}">{{ item.title }}</a>
              </li>
              {% endif %}
              {% endfor %}
            </ul>
            <ul class="nav navbar-nav ml-auto">
            </ul>
          </div>
        </div>
      </div>
    </header>
    <main class="flex-shrink-0" role="main">
{% block content %}{% endblock %}
    </main>
    <footer id="footer" class="footer mt-auto py-3">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="list-unstyled">
              {% if current_user.is_authenticated %}
              <li class="float-lg-left mr-1"><a href="/admin/">Admin</a></li>
              <li class="float-lg-left"><a href="{{ url_for('user.logout') }}">Log out</a></li>
              {% else %}
              <li class="float-lg-left"><a href="{{ url_for('user.login') }}">Log in</a></li>
              {% endif %}
              <li class="float-lg-right"><a href="#top">Back to top</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

cornerstone/templates/contact-us.html
{% extends theme('base.html') %}
{% block content %}
<article class="container contact-us">
    <h2>Contact Us</h2>
    <p>Fill in the form below, click submit, and we'll get back to you!</p>
    {% if message %}
    <div class="alert {% if message[1] == 'success' %}alert-success{% elif message[1] == 'error' %}alert-danger{% endif %}">
        {{ message[0] }}
    </div>
    {% endif %}
    <form class="form" action="" method="post">
        <div class="sweet-nectar">
            <label for="sweet-nectar">Leave this field blank</label>
            <input type="text" id="sweet-nectar" name="sweet-nectar" placeholder="Leave this field blank"/>
        </div>
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Your name" required>
        </div>
        <div class="form-group">
            <label for="email">E-mail address:</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="username@example.com" required>
        </div>
        <div class="form-group">
            <label for="subject">Subject:</label>
            <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" required>
        </div>
        <div class="form-group">
            <label for="message">Message:</label>
            <textarea class="form-control" id="message" name="message" placeholder="Type your message here..." rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</article>
{% endblock %}

cornerstone/templates/live-stream.html
{% extends theme('base.html') %}
{% block content %}
<style>
.video-container {
    height: 0;
    overflow: hidden;
    padding-bottom: 56.25%;
    padding-top: 30px;
    position: relative;
}
.video-container iframe,
.video-container video,
.video-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
</style>
<article class="container live-stream">
    <div class="row clearfix">
        <div class="col-md-12">
            <p>{{stream_general|safe}}</p>
            {% if current_stream %}
            <h3>Current Live Stream</h3>
            <div class="mb-3 text-right">
                <a href="https://www.youtube.com/watch?v={{current_stream.video_id}}" class="btn btn-primary"><i class="fab fa-youtube"></i> Watch on YouTube</a>
            </div>
            <div class="video-container clearfix">
                <iframe width="540" height="315" src="https://www.youtube.com/embed/{{current_stream.video_id}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            {% elif next_stream %}
            <h3>Next Live Stream</h3>
            <p>{{stream_before|safe}}</p>
            <div class="mb-3 text-right">
                <a href="https://www.youtube.com/watch?v={{next_stream.video_id}}" class="btn btn-primary"><i class="fab fa-youtube"></i> Watch on YouTube</a>
            </div>
            <div class="video-container clearfix">
                <iframe width="540" height="315" src="https://www.youtube.com/embed/{{next_stream.video_id}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            {% else %}
            <p>No live streams currently scheduled.</p>
            {% endif %}
        </div>
    </div>
    {% if prev_streams %}
    <div class="row mt-5">
        <div class="col-md-12">
            <h2>Previous Live Streams</h2>
        </div>
    </div>
    <div class="row mt-2">
        {% for stream in prev_streams %}
        <div class="col-sm-12 col-md-6 col-lg-4 mb-4">
            <div class="video-container">
                <iframe width="540" height="315" src="https://www.youtube.com/embed/{{stream.video_id}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</article>
{% endblock %}

cornerstone/templates/page.html
{% extends theme('base.html') %}
{% block content %}
<article class="container {{page.slug}}">
{{ page.body | safe }}
</article>
{% endblock %}

cornerstone/templates/sermon.html
{% extends theme('base.html') %}
{% block content %}
<iframe height="200px" width="100%" frameborder="no" scrolling="no" seamless src="https://player.simplecast.com/{{sermon.simplecast_id}}?dark=false"></iframe>
{% endblock %}

cornerstone/templates/sermons.html
{% extends theme('base.html') %}
{% macro no_results() %}
<div class="alert alert-warning" role="alert">
  <h5 class="alert-heading">No Sermons Found</h5>
  <p>No sermons were found by your search parameters, or there are no sermons uploaded yet.</p>
  <p>Please try making your search query less specific, or come back in a week or two.</p>
</div>
{% endmacro %}
{% block content %}
<div class="container">
  <form id="search-form" class="form-inline mb-3">
    <label class="sr-only" for="q">Search</label>
    <input type="text" name="q" id="q" placeholder="Search..." class="form-control col" value="{{ request.args.get('q', '') }}">
    <button type="submit" class="btn btn-primary ml-2">Search</button>
    <button type="button" class="btn btn-secondary ml-2" onclick="javascript:document.getElementById('q').value = '';document.getElementById('search-form').submit();">Clear</button>
  </form>
  {% if pagination %}
  {% for sermon in pagination.items %}
  <article id="sermon-{{sermon.id}}" class="card mb-3">
    <div class="card-header">
      <h5 class="card-title">{{sermon.title}} <span class="text-muted">{{sermon.scripture}}</span></h5>
      <h6 class="card-subtitle text-muted">{{sermon.date.strftime('%B %-d, %Y')}} by {{sermon.preacher}}</h6>
    </div>
    <div class="card-body">
      <p class="card-text">
        <iframe height="200px" width="100%" frameborder="no" scrolling="no" seamless src="https://player.simplecast.com/{{sermon.simplecast_id}}?dark=false"></iframe>
      </p>
      {{ sermon.description | safe }}
    </div>
    {% if sermon.topics %}
    <div class="card-footer text-justify-right">
      {% for topic in sermon.topics %}
      <a href="{{ url_for('sermons.list', q=topic.title) }}" class="badge badge-pill badge-secondary">{{ topic.title }}</a>
      {% endfor %}
    </div>
    {% endif %}
  </article>
  {% else %}
  {{ no_results() }}
  {% endfor %}
  <nav aria-label="Pagination">
    <ul class="pagination justify-content-end">
      <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
        <a class="page-link" href="{{ url_for('sermons.list', page=pagination.prev_num) }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {%- for page in pagination.iter_pages() %}
      {% if page %}
      <li class="page-item {% if page == pagination.page %}active{% endif %}"><a class="page-link" href="{{ url_for('sermons.list', page=page) }}">{{page}}</a></li>
      {% else %}
      <li class="page-item disabled">...</li>
      {% endif %}
      {%- endfor %}
      <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
        <a class="page-link" href="{{ url_for('sermons.list', page=pagination.next_num) }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
  {% else %}
  {{ no_results() }}
  {% endif %}
</div>
{% endblock %}